//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "device_command")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub device_id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub value_from: Option<i32>,
    pub value_to: Option<i32>,
    pub delay: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub reload: bool,
    pub enable: bool,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
