//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "port")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub pin: Option<i32>,
    pub port: Option<i32>,
    pub value: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub enable: bool,
    #[sea_orm(column_type = "Text")]
    pub protocol: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
